ALTER VIEW FBJ_MATRIX_REPORT
AS
SELECT FBJ_USER.Email
	,FBJ_TEST_NAME.Name
	,FBJ_RESULT.FK_TestID
	,I1.Name AS Item1
	,I2.Name AS Item2
	,FBJ_RESULT.Value
FROM FBJ_USER    
	JOIN FBJ_TEST ON FBJ_USER.PK_UserID = FBJ_TEST.FK_UserID    
	JOIN FBJ_RESULT ON FBJ_TEST.PK_TestID = FBJ_RESULT.FK_TestID   
	JOIN FBJ_ITEM I1 ON I1.PK_ItemID = FBJ_RESULT.FK_Item1ID
	JOIN FBJ_ITEM I2 ON I2.PK_ItemID = FBJ_RESULT.FK_Item2ID
	JOIN FBJ_TEST_NAME ON FBJ_TEST.FK_TestNameID = FBJ_TEST_NAME.PK_TestNameID;




