ALTER VIEW FBJ_MATRIX_ITEMS
AS
SELECT FBJ_USER.Email
,UnionResult.FK_TestID
,I1.Name AS Item1
FROM FBJ_USER    
JOIN FBJ_TEST ON FBJ_USER.PK_UserID = FBJ_TEST.FK_UserID
JOIN (SELECT FK_TestID, FK_Item1ID AS ITEM1, FK_Item2ID AS ITEM2, Value FROM FBJ_RESULT
      UNION ALL
	  SELECT FK_TestID, FK_Item2ID AS ITEM1, FK_Item1ID AS ITEM2, -1*Value  FROM FBJ_RESULT ) AS UnionResult
	  ON FBJ_TEST.PK_TestID = UnionResult.FK_TestID
JOIN FBJ_ITEM I1 ON I1.PK_ItemID = UnionResult.ITEM1
GROUP BY  FBJ_USER.Email, UnionResult.FK_TestID, I1.Name;