ALTER VIEW FBJ_TEST_NAME_LIST
AS
SELECT DISTINCT FBJ_TEST_NAME.Name, FBJ_USER.Email
FROM FBJ_TEST_NAME JOIN FBJ_TEST ON FBJ_TEST_NAME.PK_TestNameID = FBJ_TEST.FK_TestNameID
				   JOIN FBJ_USER ON FBJ_TEST.FK_UserID = FBJ_USER.PK_UserID;
